### ISSUE TITLE
search result not rendered

### ISSUE THREAD

**Issue by Clempops** [bigtunacan/rails-jquery-autocomplete#1] opened 2015-03-01 18:00 UTC
The ajax request is well sent but the results are not rendered. But by typing 'tab' the first result is set as the input value (results exist, but are not displayed)

Thanks,
Clément

**Comment by bigtunacan** [comment] 2015-03-03 01:39
Are you able to provide a link to a git repo that reproduces this?

**Comment by Kae2312** [comment] 2015-04-06 16:00
@Clempops did you resolve the problem? I have the same thing. 

I can see in my logs that the request is well sent but the results are not rendered..

**Comment by bigtunacan** [comment] 2015-04-09 02:35
@Kae2312 I have not been able to reproduce this issue.  If you can send a link to a git repo reproducing this issue it would help enable me to resolve this.

**Comment by bigtunacan** [comment] 2015-06-08 15:40
Closing since I have not received any additional information that would allow me to troubleshoot.

**Closed by bigtunacan** 2015-06-08 15:40 UTC
